using Aspire.Hosting.ApplicationModel;
using Xunit;

namespace Aspire.Hosting.OpenLdap.Tests;

/// <summary>
/// Model-level witnesses for #89: <c>OpenLdapOverlay.SyncProv(...)</c> and
/// <c>WithChangeNotifications(...)</c> declare the syncprov overlay with the measured dev-right
/// defaults, and invalid arguments fail at the .NET call instead of during container bootstrap.
/// </summary>
public class ChangeNotificationDeclarationTests
{
    [Fact]
    public void SyncProv_Defaults_Declare_The_Measured_Dev_Values()
    {
        var overlay = OpenLdapOverlay.SyncProv();

        Assert.Equal("syncprov", overlay.Name);
        Assert.Equal(["syncprov.so"], overlay.ModuleLoads);
        Assert.Equal("olcSyncProvConfig", overlay.OverlayObjectClass);
        Assert.Equal(
            [new("olcSpCheckpoint", "1 1"), new("olcSpSessionLog", "100")],
            overlay.Attributes);
    }

    [Theory]
    [InlineData("1 0")]   // the measured exit-80 bootstrap failure: minutes must be > 0
    [InlineData("100 0")]
    [InlineData("0 1")]   // ops must be positive too
    [InlineData("1")]     // not "<ops> <minutes>"
    [InlineData("1 1 1")]
    [InlineData("1  1")]  // double separator: slapd sees an empty token
    [InlineData("a b")]
    [InlineData("-1 1")]
    [InlineData("1 -1")]
    [InlineData("+1 1")]
    [InlineData(" 1 1")]
    public void SyncProv_Rejects_Malformed_And_Zero_Minute_Checkpoints(string checkpoint)
    {
        var ex = Assert.Throws<ArgumentException>(() => OpenLdapOverlay.SyncProv(checkpoint));
        Assert.Equal("checkpoint", ex.ParamName);
    }

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    public void SyncProv_Rejects_Empty_Checkpoints(string checkpoint)
    {
        Assert.ThrowsAny<ArgumentException>(() => OpenLdapOverlay.SyncProv(checkpoint));
    }

    [Fact]
    public void SyncProv_Names_The_Exit_80_Failure_It_Prevents()
    {
        // The message must explain WHY a value that looks plausible ("1 0") is rejected — the
        // in-container failure is otherwise reported against generated LDIF the user never wrote.
        var ex = Assert.Throws<ArgumentException>(() => OpenLdapOverlay.SyncProv("1 0"));
        Assert.Contains("exit code 80", ex.Message);
        Assert.Contains("<ops> <minutes>", ex.Message);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(-100)]
    public void SyncProv_Rejects_A_Non_Positive_Session_Log(int sessionLog)
    {
        Assert.Throws<ArgumentOutOfRangeException>(
            () => OpenLdapOverlay.SyncProv(sessionLog: sessionLog));
    }

    [Fact]
    public void WithChangeNotifications_Declares_The_SyncProv_Overlay()
    {
        var builder = DistributedApplication.CreateBuilder();
        var ldap = builder.AddOpenLdap("ldap").WithChangeNotifications(checkpoint: "5 2", sessionLog: 150);

        var overlay = Assert.Single(ldap.Resource.Overlays!);
        Assert.Equal("syncprov", overlay.Name);
        Assert.Contains(new KeyValuePair<string, string>("olcSpCheckpoint", "5 2"), overlay.Attributes);
        Assert.Contains(new KeyValuePair<string, string>("olcSpSessionLog", "150"), overlay.Attributes);
    }

    [Fact]
    public void WithChangeNotifications_Conflicts_With_A_Manual_SyncProv_Overlay()
    {
        var builder = DistributedApplication.CreateBuilder();
        var ldap = builder.AddOpenLdap("ldap").WithOverlay(OpenLdapOverlay.SyncProv());

        var ex = Assert.Throws<DistributedApplicationException>(() => ldap.WithChangeNotifications());
        Assert.Contains("already declared", ex.Message);
    }
}

/// <summary>
/// One container running the syncprov overlay exactly as <c>WithChangeNotifications(...)</c>
/// ships it: the declaration comes from the public <see cref="OpenLdapOverlay.SyncProv"/>
/// factory, the mounted <c>/overlays.ldif</c> is generated by the same
/// <see cref="OpenLdapOverlayConfiguration.GenerateOverlayLdif"/> the start hook writes, and the
/// bootstrap applies it online. Non-default arguments so the config witness proves the
/// requested values (not defaults baked in elsewhere) landed.
/// </summary>
public sealed class SyncProvContainerFixture : IAsyncLifetime
{
    public const string AdminPassword = "syncprov-runtime-pw";
    public const string AdminDn = "cn=admin,dc=example,dc=org";
    public const string Checkpoint = "5 2";
    public const int SessionLog = 150;

    private readonly DockerScope _scope = DockerCli.NewScope("syncprovtest");
    private string _overlayDir = string.Empty;

    /// <summary>Name of the running container. Empty until <see cref="InitializeAsync"/> runs.</summary>
    public string Container { get; private set; } = string.Empty;

    public async Task InitializeAsync()
    {
        using var cts = new CancellationTokenSource(TimeSpan.FromMinutes(10));
        var image = await BundledImage.GetAsync(cts.Token);

        _overlayDir = Directory.CreateTempSubdirectory("aspire-openldap-syncprov-").FullName;
        var overlayFile = Path.Combine(_overlayDir, "overlays.ldif");
        await File.WriteAllTextAsync(
            overlayFile,
            OpenLdapOverlayConfiguration.GenerateOverlayLdif(
                [OpenLdapOverlay.SyncProv(Checkpoint, SessionLog)]),
            cts.Token);
        DockerCli.WidenPermissionsForContainer(_overlayDir);

        Container = _scope.NewContainer();
        var run = await DockerCli.RunAsync(cts.Token,
            "run", "-d", "--name", Container,
            "-e", $"LDAP_ADMIN_PASSWORD={AdminPassword}",
            "-v", $"{overlayFile}:{OpenLdapResource.GeneratedOverlayContainerPath}:ro",
            image);
        Assert.True(run.ExitCode == 0, $"docker run failed: {run.Output}");
        await DockerCli.WaitForLdapReadyAsync(Container, AdminDn, AdminPassword, cts.Token);
    }

    public Task DisposeAsync()
    {
        _scope.Dispose();
        if (_overlayDir.Length > 0 && Directory.Exists(_overlayDir))
        {
            Directory.Delete(_overlayDir, recursive: true);
        }
        return Task.CompletedTask;
    }
}

/// <summary>
/// Docker-driven runtime witnesses for #89. The facts assert both that the requested syncprov
/// configuration landed in cn=config AND that the overlay actually notifies: an RFC 4533
/// refreshAndPersist client (<c>ldapsearch -E sync=rp</c>, the CLI baseline the #53 spike
/// verified) observes a persist-stage notification for a mutation made after its refresh
/// completed.
/// </summary>
[Trait("Category", "Integration")]
public class ChangeNotificationRuntimeTests(SyncProvContainerFixture fixture)
    : IClassFixture<SyncProvContainerFixture>
{
    [Fact]
    public async Task Overlay_Lands_In_Config_With_The_Requested_Values()
    {
        using var cts = new CancellationTokenSource(TimeSpan.FromMinutes(5));

        // Attribute names come back in slapd's canonical casing (olcSpSessionlog), not the
        // spelling the generator wrote — compare case-insensitively (same trap as ppolicy).
        var config = await DockerCli.RunAsync(cts.Token,
            "exec", fixture.Container, "ldapsearch", "-Q", "-Y", "EXTERNAL", "-H", "ldapi:///",
            "-b", OpenLdapResource.MdbDatabaseDn, "(objectClass=olcSyncProvConfig)");
        Assert.True(config.ExitCode == 0, $"cn=config syncprov search failed: {config.Output}");
        Assert.Contains($"olcSpCheckpoint: {SyncProvContainerFixture.Checkpoint}",
            config.Output, StringComparison.OrdinalIgnoreCase);
        Assert.Contains($"olcSpSessionLog: {SyncProvContainerFixture.SessionLog}",
            config.Output, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task RefreshAndPersist_Client_Observes_A_Persist_Stage_Notification()
    {
        using var cts = new CancellationTokenSource(TimeSpan.FromMinutes(5));

        const string userDn = "cn=user01,ou=users,dc=example,dc=org";
        const string marker = "sync-witness-42";

        // One in-container script so the refreshAndPersist search, the mutation, and the
        // observation share a filesystem. Ordering is enforced by polling, not sleeps:
        // the modify is only sent AFTER the refresh stage delivered user01, so the marker
        // arriving afterwards can only be a persist-stage notification. stdbuf keeps
        // ldapsearch line-buffered into the file; the final cat surfaces everything observed.
        var script =
            "out=/tmp/sync-witness.out\n" +
            "stdbuf -oL -eL timeout 120 ldapsearch -x -H " + DockerCli.InContainerLdapUri +
            $" -D '{SyncProvContainerFixture.AdminDn}' -w '{SyncProvContainerFixture.AdminPassword}'" +
            $" -b dc=example,dc=org -E 'sync=rp' '(cn=user01)' description > \"$out\" 2>&1 &\n" +
            "sync_pid=$!\n" +
            "for i in $(seq 1 60); do grep -q 'dn: cn=user01' \"$out\" && break; sleep 0.5; done\n" +
            "grep -q 'dn: cn=user01' \"$out\" || { echo 'REFRESH-STAGE ENTRY NEVER ARRIVED'; kill $sync_pid; cat \"$out\"; exit 1; }\n" +
            $"printf 'dn: {userDn}\\nchangetype: modify\\nreplace: description\\ndescription: {marker}\\n' | " +
            "ldapmodify -x -H " + DockerCli.InContainerLdapUri +
            $" -D '{SyncProvContainerFixture.AdminDn}' -w '{SyncProvContainerFixture.AdminPassword}' > /dev/null\n" +
            $"for i in $(seq 1 60); do grep -q '{marker}' \"$out\" && break; sleep 0.5; done\n" +
            "kill $sync_pid 2>/dev/null\n" +
            "cat \"$out\"\n";

        var witness = await DockerCli.RunAsync(cts.Token, "exec", fixture.Container, "bash", "-c", script);
        Assert.True(witness.ExitCode == 0, $"sync=rp witness script failed: {witness.Output}");

        // The marker value did not exist when the search started, so its presence in the
        // sync output is a notification delivered during the persist stage.
        Assert.Contains(marker, witness.Output);

        // And the entry arrived twice: once from the refresh stage (pre-mutation), once as
        // the persist-stage notification.
        Assert.True(
            CountOccurrences(witness.Output, $"dn: {userDn}") >= 2,
            $"expected the refresh-stage entry AND a persist-stage notification: {witness.Output}");
    }

    private static int CountOccurrences(string text, string value)
    {
        var count = 0;
        for (var i = text.IndexOf(value, StringComparison.Ordinal); i >= 0;
             i = text.IndexOf(value, i + value.Length, StringComparison.Ordinal))
        {
            count++;
        }
        return count;
    }
}
