<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="bunit" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aspire.LdapAdmin.AppHost\Aspire.LdapAdmin.AppHost.csproj" />
    <ProjectReference Include="..\Aspire.LdapAdmin.Core\Aspire.LdapAdmin.Core.csproj" />
    <ProjectReference Include="..\Aspire.OpenLdap\Aspire.OpenLdap.csproj" />
    <ProjectReference Include="..\Aspire.LdapAdmin.Web\Aspire.LdapAdmin.Web.csproj" />
  </ItemGroup>

</Project>
