using LdifDotNet;

namespace Aspire.Hosting.ApplicationModel.Seeding;

internal static class LdapSeedLdifGenerator
{
    /// <summary>
    /// Writer options for every LDIF file this integration generates. No version line and no
    /// line folding: the files are consumed by ldapadd/ldapmodify inside the container (which
    /// need neither) and unfolded output stays grep-friendly when debugging a failed load.
    /// LdifWriter always emits LF line endings, which the Linux container requires.
    /// </summary>
    internal static readonly LdifWriterOptions WriterOptions = new()
    {
        IncludeVersionLine = false,
        WrapColumn = null,
    };

    public static string Generate(OpenLdapResource resource, LdapSeedModel model)
    {
        var records = new List<LdifRecord> { RootEntry(resource) };

        foreach (var ou in model.OrganizationalUnits.OrderBy(o => o.Name, StringComparer.Ordinal))
        {
            records.Add(new LdifContentRecord(
                Dn.Combine(Dn.Rdn("ou", ou.Name), resource.BaseDn),
                new LdifAttribute("objectClass", "organizationalUnit"),
                new LdifAttribute("ou", ou.Name)));
        }

        foreach (var user in model.Users.OrderBy(u => u.Uid, StringComparer.Ordinal))
        {
            var attributes = new List<LdifAttribute>
            {
                new("objectClass", "inetOrgPerson", "organizationalPerson", "person", "top"),
                new("uid", user.Uid),
                new("cn", user.Cn),
                new("sn", user.Sn),
            };
            if (user.Mail is not null)
            {
                attributes.Add(new("mail", user.Mail));
            }
            // Stored hashed ({SSHA}) so the directory never holds the cleartext at rest;
            // slapd verifies binds against the hash natively. Pre-hashed values ({SCHEME}...)
            // pass through verbatim.
            attributes.Add(new("userPassword", LdapPasswordHasher.ToUserPasswordValue(user.Password)));
            records.Add(new LdifContentRecord(UserDn(resource, user), attributes));
        }

        foreach (var group in model.Groups.OrderBy(g => g.Cn, StringComparer.Ordinal))
        {
            var members = group.Members.Select(member =>
                (LdifValue)(member.Contains('=', StringComparison.Ordinal)
                    ? member
                    : ResolveUserDn(resource, model, member)));
            records.Add(new LdifContentRecord(
                GroupDn(resource, group),
                new LdifAttribute("objectClass", "groupOfNames", "top"),
                new LdifAttribute("cn", group.Cn),
                new LdifAttribute("member", members)));
        }

        return "# Generated by Aspire.Hosting.OpenLdap. Do not edit; declarations live in your AppHost.\n\n"
            + LdifWriter.WriteToString(records, WriterOptions);
    }

    // When /ldifs is non-empty, the container's init skips its default tree creation —
    // so the root entry for the base DN never gets created. Emit it here so the OUs/users
    // below have a parent to attach to. Mirrors the existing tree.ldif format.
    private static LdifContentRecord RootEntry(OpenLdapResource resource)
    {
        // Parse the base DN into ordered, unescaped RDN components (escape-aware, so an
        // escaped comma in a value like o=Acme\, Inc. no longer splits mid-value). The
        // LEADING RDN names the root entry, so it drives the object class and must appear
        // as an attribute; dc=/o=/c= are the supported forms, enforced by
        // OpenLdapDnValidation at model construction.
        var rdns = Dn.Parse(resource.BaseDn);
        var root = rdns[0].SoleAttribute;

        var attributes = new List<LdifAttribute>();
        if (string.Equals(root.Type, "dc", StringComparison.OrdinalIgnoreCase))
        {
            // organization requires an o attribute; use the first o= elsewhere in the DN,
            // falling back to the dc value.
            var o = root.Value;
            foreach (var rdn in rdns.Skip(1))
            {
                var match = rdn.Attributes.FirstOrDefault(a => string.Equals(a.Type, "o", StringComparison.OrdinalIgnoreCase));
                if (match.Value is not null)
                {
                    o = match.Value;
                    break;
                }
            }
            attributes.Add(new("objectClass", "dcObject", "organization"));
            attributes.Add(new("dc", root.Value));
            attributes.Add(new("o", o));
        }
        else if (string.Equals(root.Type, "o", StringComparison.OrdinalIgnoreCase))
        {
            attributes.Add(new("objectClass", "organization"));
            attributes.Add(new("o", root.Value));
        }
        else if (string.Equals(root.Type, "c", StringComparison.OrdinalIgnoreCase))
        {
            attributes.Add(new("objectClass", "country"));
            attributes.Add(new("c", root.Value));
        }
        else
        {
            throw new InvalidOperationException(
                $"Base DN '{resource.BaseDn}' starts with '{root.Type}=', which is not a supported root naming attribute (dc=, o=, c=).");
        }

        return new LdifContentRecord(resource.BaseDn, attributes);
    }

    private static string UserDn(OpenLdapResource resource, SeedUserEntry user)
        => Dn.Combine(
            Dn.Rdn("uid", user.Uid),
            user.OrganizationalUnit is { } ou ? Dn.Rdn("ou", ou) : string.Empty,
            resource.BaseDn);

    private static string GroupDn(OpenLdapResource resource, SeedGroupEntry group)
        => Dn.Combine(
            Dn.Rdn("cn", group.Cn),
            group.OrganizationalUnit is { } ou ? Dn.Rdn("ou", ou) : string.Empty,
            resource.BaseDn);

    private static string ResolveUserDn(OpenLdapResource resource, LdapSeedModel model, string uid)
    {
        var user = model.Users.First(u => string.Equals(u.Uid, uid, StringComparison.OrdinalIgnoreCase));
        return UserDn(resource, user);
    }
}
