using System.Text;

namespace Aspire.Hosting.ApplicationModel.Seeding;

internal static class LdapSeedLdifGenerator
{
    // LDIF is consumed inside a Linux container; force LF newlines so we don't depend on
    // ldapadd being lenient about CRLF when the host is Windows.
    private const string Nl = "\n";

    public static string Generate(OpenLdapResource resource, LdapSeedModel model)
    {
        var sb = new StringBuilder();
        sb.Append("# Generated by Aspire.Hosting.OpenLdap. Do not edit; declarations live in your AppHost.").Append(Nl);
        sb.Append(Nl);

        // When /ldifs is non-empty, the container's init skips its default tree creation —
        // so the root entry for the base DN never gets created. Emit it here so the OUs/users
        // below have a parent to attach to. Mirrors the existing tree.ldif format.
        AppendRootEntry(sb, resource);

        foreach (var ou in model.OrganizationalUnits.OrderBy(o => o.Name, StringComparer.Ordinal))
        {
            Append(sb, "dn", $"ou={LdifEncoder.EscapeDnValue(ou.Name)},{resource.BaseDn}");
            Append(sb, "objectClass", "organizationalUnit");
            Append(sb, "ou", ou.Name);
            sb.Append(Nl);
        }

        foreach (var user in model.Users.OrderBy(u => u.Uid, StringComparer.Ordinal))
        {
            Append(sb, "dn", UserDn(resource, user));
            Append(sb, "objectClass", "inetOrgPerson");
            Append(sb, "objectClass", "organizationalPerson");
            Append(sb, "objectClass", "person");
            Append(sb, "objectClass", "top");
            Append(sb, "uid", user.Uid);
            Append(sb, "cn", user.Cn);
            Append(sb, "sn", user.Sn);
            if (user.Mail is not null)
            {
                Append(sb, "mail", user.Mail);
            }
            Append(sb, "userPassword", user.Password);
            sb.Append(Nl);
        }

        foreach (var group in model.Groups.OrderBy(g => g.Cn, StringComparer.Ordinal))
        {
            Append(sb, "dn", GroupDn(resource, group));
            Append(sb, "objectClass", "groupOfNames");
            Append(sb, "objectClass", "top");
            Append(sb, "cn", group.Cn);
            foreach (var member in group.Members)
            {
                var memberDn = member.Contains('=', StringComparison.Ordinal)
                    ? member
                    : ResolveUserDn(resource, model, member);
                Append(sb, "member", memberDn);
            }
            sb.Append(Nl);
        }

        return sb.ToString();
    }

    private static void Append(StringBuilder sb, string attribute, string value)
        => LdifEncoder.AppendAttribute(sb, attribute, value, Nl);

    private static void AppendRootEntry(StringBuilder sb, OpenLdapResource resource)
    {
        string? dc = null;
        string? o = null;
        foreach (var part in resource.BaseDn.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries))
        {
            if (dc is null && part.StartsWith("dc=", StringComparison.OrdinalIgnoreCase))
            {
                dc = part[3..];
            }
            else if (o is null && part.StartsWith("o=", StringComparison.OrdinalIgnoreCase))
            {
                o = part[2..];
            }
        }

        Append(sb, "dn", resource.BaseDn);
        if (dc is not null)
        {
            Append(sb, "objectClass", "dcObject");
        }
        Append(sb, "objectClass", "organization");
        if (dc is not null)
        {
            Append(sb, "dc", dc);
        }
        Append(sb, "o", o ?? dc ?? "organization");
        sb.Append(Nl);
    }

    private static string UserDn(OpenLdapResource resource, SeedUserEntry user)
        => user.OrganizationalUnit is { } ou
            ? $"uid={LdifEncoder.EscapeDnValue(user.Uid)},ou={LdifEncoder.EscapeDnValue(ou)},{resource.BaseDn}"
            : $"uid={LdifEncoder.EscapeDnValue(user.Uid)},{resource.BaseDn}";

    private static string GroupDn(OpenLdapResource resource, SeedGroupEntry group)
        => group.OrganizationalUnit is { } ou
            ? $"cn={LdifEncoder.EscapeDnValue(group.Cn)},ou={LdifEncoder.EscapeDnValue(ou)},{resource.BaseDn}"
            : $"cn={LdifEncoder.EscapeDnValue(group.Cn)},{resource.BaseDn}";

    private static string ResolveUserDn(OpenLdapResource resource, LdapSeedModel model, string uid)
    {
        var user = model.Users.First(u => string.Equals(u.Uid, uid, StringComparison.OrdinalIgnoreCase));
        return UserDn(resource, user);
    }
}
