using LdifDotNet;

namespace Aspire.Hosting.ApplicationModel.Seeding;

internal static class LdapSeedLdifGenerator
{
    /// <summary>
    /// Writer options for every LDIF file this integration generates. No version line and no
    /// line folding: the files are consumed by ldapadd/ldapmodify inside the container (which
    /// need neither) and unfolded output stays grep-friendly when debugging a failed load.
    /// LdifWriter always emits LF line endings, which the Linux container requires.
    /// </summary>
    internal static readonly LdifWriterOptions WriterOptions = new()
    {
        IncludeVersionLine = false,
        WrapColumn = null,
    };

    public static string Generate(OpenLdapResource resource, LdapSeedModel model)
    {
        var records = new List<LdifRecord> { RootEntry(resource) };

        foreach (var ou in model.OrganizationalUnits.OrderBy(o => o.Name, StringComparer.Ordinal))
        {
            records.Add(new LdifContentRecord(
                Dn.Combine(Dn.Rdn("ou", ou.Name), resource.BaseDn),
                new LdifAttribute("objectClass", "organizationalUnit"),
                new LdifAttribute("ou", ou.Name)));
        }

        foreach (var user in model.Users.OrderBy(u => u.Uid, StringComparer.Ordinal))
        {
            var attributes = new List<LdifAttribute>
            {
                new("objectClass", "inetOrgPerson", "organizationalPerson", "person", "top"),
                new("uid", user.Uid),
                new("cn", user.Cn),
                new("sn", user.Sn),
            };
            if (user.Mail is not null)
            {
                attributes.Add(new("mail", user.Mail));
            }
            attributes.Add(new("userPassword", user.Password));
            records.Add(new LdifContentRecord(UserDn(resource, user), attributes));
        }

        foreach (var group in model.Groups.OrderBy(g => g.Cn, StringComparer.Ordinal))
        {
            var members = group.Members.Select(member =>
                (LdifValue)(member.Contains('=', StringComparison.Ordinal)
                    ? member
                    : ResolveUserDn(resource, model, member)));
            records.Add(new LdifContentRecord(
                GroupDn(resource, group),
                new LdifAttribute("objectClass", "groupOfNames", "top"),
                new LdifAttribute("cn", group.Cn),
                new LdifAttribute("member", members)));
        }

        return "# Generated by Aspire.Hosting.OpenLdap. Do not edit; declarations live in your AppHost.\n\n"
            + LdifWriter.WriteToString(records, WriterOptions);
    }

    // When /ldifs is non-empty, the container's init skips its default tree creation —
    // so the root entry for the base DN never gets created. Emit it here so the OUs/users
    // below have a parent to attach to. Mirrors the existing tree.ldif format.
    private static LdifContentRecord RootEntry(OpenLdapResource resource)
    {
        // Parse the base DN into ordered, unescaped RDN components so an escaped comma
        // inside a value (o=Acme\, Inc.) no longer splits mid-value, and the extracted
        // dc/o values are the real (unescaped) values.
        string? dc = null;
        string? o = null;
        foreach (var rdn in Dn.Parse(resource.BaseDn))
        {
            foreach (var atav in rdn.Attributes)
            {
                if (dc is null && string.Equals(atav.Type, "dc", StringComparison.OrdinalIgnoreCase))
                {
                    dc = atav.Value;
                }
                else if (o is null && string.Equals(atav.Type, "o", StringComparison.OrdinalIgnoreCase))
                {
                    o = atav.Value;
                }
            }
        }

        var attributes = new List<LdifAttribute>
        {
            dc is not null
                ? new("objectClass", "dcObject", "organization")
                : new("objectClass", "organization"),
        };
        if (dc is not null)
        {
            attributes.Add(new("dc", dc));
        }
        attributes.Add(new("o", o ?? dc ?? "organization"));
        return new LdifContentRecord(resource.BaseDn, attributes);
    }

    private static string UserDn(OpenLdapResource resource, SeedUserEntry user)
        => Dn.Combine(
            Dn.Rdn("uid", user.Uid),
            user.OrganizationalUnit is { } ou ? Dn.Rdn("ou", ou) : string.Empty,
            resource.BaseDn);

    private static string GroupDn(OpenLdapResource resource, SeedGroupEntry group)
        => Dn.Combine(
            Dn.Rdn("cn", group.Cn),
            group.OrganizationalUnit is { } ou ? Dn.Rdn("ou", ou) : string.Empty,
            resource.BaseDn);

    private static string ResolveUserDn(OpenLdapResource resource, LdapSeedModel model, string uid)
    {
        var user = model.Users.First(u => string.Equals(u.Uid, uid, StringComparison.OrdinalIgnoreCase));
        return UserDn(resource, user);
    }
}
